apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployments
spec:
   selector:
      matchLabels:
         app: nginx
   replicas: 4
   template:
      metadata:
        labels:
            app: nginx
      spec:
         containers:
            - name: nginx-cont
              image: nginx:1.14.2
              ports:
                - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: nginx-service
spec: 
  type: NodePort
  selector:
          app: nginx
  ports:
     - port: 80
       targetPort: 80
       nodePort: 30007
