apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-volume
spec:
  storageClassName: local
  capacity:
    storage: 200Mi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /kube-volume-2 
