apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: pvc-volume-sai
spec:
   storageClassName: local
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
          storage: 100Mi

