apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: veeraraghavan
spec:
  storageClassName: hanuman
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi      
