apiVersion: v1
kind: Pod
metadata: 
  name: saipod
spec:
  containers:
  - name: saipod         
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes: 
  - name: foo
    secret: 
      secretName: mysecret  
